version: '3.7'
services:
  postgres:
    image: postgres:9.6.10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gpw_radar
    networks:
    - gpw
  rabbit:
    build:
      context: ./configs/rabbitmq/docker
      dockerfile: Dockerfile
    networks:
    - gpw
  es:
    build:
      context: ./configs/elasticsearch/docker
      dockerfile: Dockerfile
    command: -Des.network.host=0.0.0.0
    networks:
      - gpw
  rss:
    build:
      context: ./target/rss
      dockerfile: Dockerfile
    networks:
      - gpw
  gpw_app:
    build:
      context: ./target/web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rss
      - rabbit
      - es
      - postgres
    networks:
      - gpw
networks:
  gpw:
    driver: "bridge"